version: '2'

volumes:
    weston:

services:

  weston:
    restart: always
    build: ./weston
    privileged: true
    environment:
      WPE_WESTON_SHELL: kiosk
      WPE_WESTON_OUTPUT_MAX_WIDTH: 1920
      WPE_WESTON_OUTPUT_MAX_HEIGHT: 1080
    volumes:
      - 'weston:/run/weston'

  wpe:
    restart: always
    build: ./wpe
    privileged: true
    environment:
      WPE_COG_PLATFORM_FDO_VIEW_FULLSCREEN: 1
      WPE_COG_PLATFORM_FDO_VIEW_HEIGHT: 1080
      WPE_COG_PLATFORM_FDO_VIEW_WIDTH: 1920
    ports:
      - 8080:8080
      - 12321:12321
    volumes:
      - 'weston:/run/weston'

  notify:
    restart: "on-failure"
    privileged: true
    build: ./notify
