#!/bin/sh

export WAYLAND_DISPLAY="wayland-0"
export XDG_RUNTIME_DIR=/run/weston/xdg_runtime

CPU_SCALING_GOVERNOR=${CPU_SCALING_GOVERNOR:-performance}

WAYLAND_INFO="/usr/bin/waylandeglinfo"

for i in $(ls /sys/devices/system/cpu/cpu*/cpufreq/scaling_governor)
do
    echo "${CPU_SCALING_GOVERNOR}" > $i
done

udevd &
udevadm trigger

# /var/tmp points to /var/volatile/tmp  what it doesn't exist
# /var/tmp is need for gstreamer to download chunks of videos
mkdir -p /var/volatile/tmp  || rm -rf /var/volatile/tmp/*

# Wait for the Wayland compositor is available
if test -f "${WAYLAND_INFO}"
then
    while ! ${WAYLAND_INFO}
    do
        echo "Waiting for the Wayland compositor is ready ..."
        sleep 0.5
    done
else
    # If waylandeglinfo is not available in the image let's rely in the
    # creation of the wayland socket in the XDG runtime directory.
    while ! test -S ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY}
    do
        echo "Waiting for the ${XDG_RUNTIME_DIR}/${WAYLAND_DISPLAY} socket ..."
        sleep 0.5
    done
fi

# Launch a D-Bus daemon for cogctl
mkdir -p /run/dbus/
dbus-launch > /run/dbus/env
export $(cat /run/dbus/env)


# disable touch screen
export WPE_BCMRPI_TOUCH=0

# mount the token folder, if we're on balena
if [ "$BALENA" == "1" ]; then
  mkdir -p /mnt/data
  mount /dev/mmcblk0p6 /mnt/data
fi

# read the refresh token file
if [[ $REFRESH_TOKEN_FILE ]]; then
  if [[ -f "$REFRESH_TOKEN_FILE" ]]; then
    export REFRESH_TOKEN=`cat $REFRESH_TOKEN_FILE`
  fi
fi

if [[ $REFRESH_TOKEN ]]; then
    export WPE_URL="$WPE_URL?token=$REFRESH_TOKEN"
fi

# Start browser
cog-fdo "file:///var/lib/public_html/index.html?url=${WPE_URL}"

# Start Tohora
./tohora 8080 "cog-open"

